///////  men data ////////
let productsDB =  [
    {
    id : 1,
    title:"ADIDAS LOGO T-SHIRT" ,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
    number: 8 , 
    size:["Small" , "Mediam" ,  "Large"],
    price : 12.00 ,
    imgUrl:"../imgs/T-shirt black.jpg",
    imgUrl2:"../imgs/T-shirt White.jpg",
    quantity: 1 ,
    isMe : 'N',
    },
    {
    id : 2,
    title:"Sweat Shirt" ,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
    number: 10 , 
    size:["Small" , "Mediam" ,  "Large"],
    price : 23.00 ,
    imgUrl:"../imgs/Sweat Shirt 2.jpg",
    imgUrl2:"../imgs/Sweat Shirt.jpg",
    quantity: 1 ,
    isMe : 'N',
    },
    {
    id : 3,
    title:"Casual Baseball Jacket" ,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",

    number: 6 , 
    size:["Small" , "Mediam" ,  "Large"],
    price : 10.00 ,
    imgUrl:"../imgs/Casual Baseball Jacket.jpg",
    imgUrl2:"../imgs/Casual Baseball Jacket 2.jpg",
    quantity: 1 ,
    isMe : 'N',
    },
    {
    id : 4,
    title:"ADIDAS SPORTSWEAR SNEAKERS" ,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
    isMe : 'N',
    number: 2 , 
    size:["Small" , "Mediam" ,  "Large"],
    price : 16.00 ,
    imgUrl:"../imgs/ADIDAS SPORTSWEAR SNEAKERS 2.jpg",
    imgUrl2:"../imgs/ADIDAS SPORTSWEAR SNEAKERS.jpg",
    quantity: 1 ,
    },
    {
    id : 5,
    title:"Digital Watch Stainless Steel" ,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
    isMe : 'N',
    number: 5, 
    size:["Small" , "Mediam" ,  "Large"],
    price : 24.00 ,
    imgUrl:"../imgs/Digital Watch Stainless Steel.jpg",
    imgUrl2:"../imgs/Digital Watch Stainless Steel 2.jpg",
    quantity: 1 ,
    },
    {
    id : 6,
    title:"High Neck Pullover White" ,
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
        isMe : 'N',
    number: 4 , 
    size:["Small" , "Mediam" ,  "Large"],
    price : 15.00 ,
    imgUrl:"../imgs/High Neck Pullover White.jpg",
    imgUrl2:"../imgs/High Neck Pullover black.jpg",
    quantity: 1 ,
    },
    {
      id : 7,
      title:"سويت شيرت اسود بسوسته وكابيشو" ,
      desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
      isMe : 'N',
      number: 8 , 
      size:["Small" , "Mediam" ,  "Large"],
      price : 12.00 ,
      imgUrl:"../imgs/سويت شيرت اسود بسوسته وكابيشو .jpg",
      imgUrl2:"../imgs/سويت شيرت اسود بسوسته وكابيشو 1.jpg",
      quantity: 1 ,
      },
      {
      id : 8,
      title:"فيست اسو" ,
      desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
      isMe : 'N',
      number: 10 , 
      size:["Small" , "Mediam" ,  "Large"],
      price : 23.00 ,
      imgUrl:"../imgs/فيست اسود.jpg",
      imgUrl2:"../imgs/فيست اسود1.jpg",
      quantity: 1 ,
      },
      {
      id : 9,
      title:"Heather Grey" ,
      desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
      number: 6 , 
      size:["Small" , "Mediam" ,  "Large"],
      price : 10.00 ,
      imgUrl:"../imgs/Heather Grey.jpg",
      imgUrl2:"../imgs/Heather Grey1.jpg",
      quantity: 1 ,
      isMe : 'N',
      },
  ]


  ///////////// Kids /////
  let products_KidsDB =  [
    {
    id : 20,
    title:"هاي كول صوف أولادي." ,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
    isMe : 'N',
    number: 8 , 
    size:["Small" , "Mediam" ,  "Large"],
    price : 12.00 ,
    imgUrl:"../imgs/هاي كول صوف أولادي.jpg",
    imgUrl2:"../imgs/هاي كول صوف أولادي1.jpg",
    quantity: 1 ,
    },
    {
    id : 21,
    title:"ترنج أطفال بناتي" ,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
    isMe : 'N',
    number: 10 , 
    size:["Small" , "Mediam" ,  "Large"],
    price : 23.00 ,
    imgUrl:"../imgs/ترنج أطفال بناتي.jpg",
    imgUrl2:"../imgs/ترنج أطفال بناتي1.jpg",
    quantity: 1 ,
    },
    {
    id : 22,
    title:"ترنج أولادي رياضي" ,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
    isMe : 'N',
    number: 6 , 
    size:["Small" , "Mediam" ,  "Large"],
    price : 10.00 ,
    imgUrl:"../imgs/ترنج أولادي رياضي.jpg",
    imgUrl2:"../imgs/ترنج أولادي رياضي1.jpg",
    quantity: 1 ,
    },
    {
    id : 23,
    title:"جاكيت أولادي" ,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
    isMe : 'N',
    number: 2 , 
    size:["Small" , "Mediam" ,  "Large"],
    price : 16.00 ,
    imgUrl:"../imgs/جاكيت أولادي .jpg",
    imgUrl2:"../imgs/جاكيت أولادي 1.jpg",
    quantity: 1 ,
    },
    {
    id : 24,
    title:"هاي كول صوف بناتي" ,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
    isMe : 'N',
    number: 5, 
    size:["Small" , "Mediam" ,  "Large"],
    price : 24.00 ,
    imgUrl:"../imgs/هاي كول صوف بناتي .jpg",
    imgUrl2:"../imgs/هاي كول صوف بناتي1 .jpg",
    quantity: 1 ,
    },
    {
    id : 25,
    title:"روب من الفيلور بتصميم أرنب" ,
    number: 4 , 
    size:["Small" , "Mediam" ,  "Large"],
    price : 15.00 ,
    imgUrl:"../imgs/روب من الفيلور بتصميم أرنب.jpg",
    imgUrl2:"../imgs/روب من الفيلور بتصميم أرنب1.jpg",
    quantity: 1 ,
    },
    {
      id : 26,
      title:"Girl Orange dress1" ,
      desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
      isMe : 'N',
      number: 8 , 
      size:["Small" , "Mediam" ,  "Large"],
      price : 12.00 ,
      imgUrl:"../imgs/Girl Orange dress.jpg",
      imgUrl2:"../imgs/Girl Orange dress1.jpg",
      quantity: 1 ,
      },
    
  ]
/////////////// Women ///////////////////
dom_Women = document.querySelector("#new-arrivals_Women");
console.log(dom_Women)
let products_WomenDB =  [
  {
  id : 37,
  title:"Green women's dress" ,
  desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
  isMe : 'N',
  number: 8 , 
  size:["Small" , "Mediam" ,  "Large"],
  price : 12.00 ,
  imgUrl:"../imgs/Green women's dress.jpg",
  imgUrl2:"../imgs/Green women's dress1.jpg",
  quantity: 1 ,
  },
  {
  id : 38,
  title:"Grey Pullover" ,
  desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
  isMe : 'N',
  number: 10 , 
  size:["Small" , "Mediam" ,  "Large"],
  price : 23.00 ,
  imgUrl:"../imgs/Grey Pullover.jpg",
  imgUrl2:"../imgs/Grey Pullover1.jpg",
  quantity: 1 ,
  },
  {
  id : 39,
  title:"Shawl - Brown" ,
  number: 6 , 
  size:["Small" , "Mediam" ,  "Large"],
  desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
  isMe : 'N',
  price : 10.00 ,
  imgUrl:"../imgs/Shawl - Brown.jpg",
  imgUrl2:"../imgs/Shawl - Brown1.jpg",
  quantity: 1 ,
  },
  {
  id : 40,
  title:"Woman Black Coat" ,
  desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
  isMe : 'N',
  number: 2 , 
  size:["Small" , "Mediam" ,  "Large"],
  price : 16.00 ,
  imgUrl:"../imgs/Woman Black Coat.jpg",
  imgUrl2:"../imgs/Woman Black Coat1.jpg",
  quantity: 1 ,
  },
  {
  id : 41,
  title:"Black Sweat Shirt" ,
  number: 5, 
  desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
  size:["Small" , "Mediam" ,  "Large"],
  price : 24.00 ,
  imgUrl:"../imgs/Black Sweat Shirt.jpg",
  imgUrl2:"../imgs/Black Sweat Shirt1.jpg",
  quantity: 1 ,
  },
  {
  id : 42,
  title:"Cardigan - Dark Grey" ,
  desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet suscipit quos magnam, sequi deserunt, ex illo natus saepe ratione odio fugit, architecto culpa molestias vero labore placeat eligendi reprehenderit pariatur!",
  isMe : 'N',
  number: 4 , 
  size:["Small" , "Mediam" ,  "Large"],
  price : 15.00 ,
  imgUrl:"../imgs/Cardigan - Dark Grey.jpg",
  imgUrl2:"../imgs/Cardigan - Dark Grey1.jpg",
  quantity: 1 ,
  },
]

//  localStorage.setItem("products" , JSON.stringify(productsDB));
//  localStorage.setItem("products_Women" , JSON.stringify(products_WomenDB));
//  localStorage.setItem("products_Kids" , JSON.stringify(products_KidsDB));